version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:17.2
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'npm installing!'
      - run:
          name: The Second Step
          command: |
            npm install
      - run:
          name: The Third Step
          command: |
            CI=true npm run build
  test:
    docker:
      - image: cimg/node:17.2
    steps:
      - checkout
      - run:
          command: |
            echo "testing stuff"
      - run:
          command: |
            npm install
      - run:
          command: |
            npm test
  hithere:
    docker:
      - image: cimg/node:17.2
    steps:
      - run:
          command: |
            echo "hi there"
  sally:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Double Trouble'
workflows:
  version: 2.1
  build_test_and_lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere
