version: 2.1
jobs:
  bobby:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
  sally:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Double Trouble'
workflows:
  version: 2.1
  bobby_sally:
    jobs:
      - bobby
      - sally
